-- Insert sample content items for demonstration
INSERT INTO content_items (
    id,
    user_id,
    organization_id,
    title,
    description,
    content,
    type,
    status,
    priority,
    tags,
    viral_hook,
    viral_analysis_score,
    predicted_engagement,
    audience_match,
    competitor_comparison,
    platforms,
    views,
    likes,
    comments,
    shares,
    is_starred,
    is_flagged,
    created_at,
    updated_at
) VALUES 
(
    '550e8400-e29b-41d4-a716-446655440001',
    (SELECT id FROM auth.users LIMIT 1),
    (SELECT id FROM organizations LIMIT 1),
    'AI Revolution in Small Business',
    'Comprehensive guide on how AI is transforming small businesses across industries',
    'In this comprehensive guide, we explore how artificial intelligence is revolutionizing the way small businesses operate, from customer service automation to predictive analytics...',
    'post',
    'ideas',
    'high',
    ARRAY['AI', 'Business', 'Guide', 'Transformation'],
    'The AI revolution isn''t coming - it''s already here, and small businesses are winning big!',
    85,
    8.2,
    92,
    78,
    ARRAY['LinkedIn', 'Twitter', 'Medium'],
    0,
    0,
    0,
    0,
    true,
    false,
    NOW() - INTERVAL '2 days',
    NOW() - INTERVAL '1 day'
),
(
    '550e8400-e29b-41d4-a716-446655440002',
    (SELECT id FROM auth.users LIMIT 1),
    (SELECT id FROM organizations LIMIT 1),
    'Customer Service Automation Script',
    'Video script for demonstrating AI-powered customer service automation',
    'HOOK: "What if I told you that 90% of customer service calls could be handled by AI..." [SCENE 1: Problem presentation]...',
    'script',
    'in-progress',
    'medium',
    ARRAY['Customer Service', 'Automation', 'AI', 'Script'],
    'This AI handles 90% of customer complaints (and customers LOVE it)',
    78,
    7.5,
    88,
    82,
    ARRAY['YouTube', 'TikTok', 'Instagram'],
    0,
    0,
    0,
    0,
    false,
    false,
    NOW() - INTERVAL '5 days',
    NOW() - INTERVAL '3 hours'
),
(
    '550e8400-e29b-41d4-a716-446655440003',
    (SELECT id FROM auth.users LIMIT 1),
    (SELECT id FROM organizations LIMIT 1),
    'ROI Calculator Demo Video',
    'Screen recording showing how to use our ROI calculator for AI implementations',
    'This video demonstrates the step-by-step process of calculating ROI for AI automation projects...',
    'video',
    'review',
    'high',
    ARRAY['ROI', 'Calculator', 'Demo', 'Tutorial'],
    'Calculate your AI ROI in under 60 seconds (results will shock you)',
    91,
    9.1,
    95,
    87,
    ARRAY['YouTube', 'LinkedIn', 'Website'],
    0,
    0,
    0,
    0,
    false,
    false,
    NOW() - INTERVAL '7 days',
    NOW() - INTERVAL '2 days'
),
(
    '550e8400-e29b-41d4-a716-446655440004',
    (SELECT id FROM auth.users LIMIT 1),
    (SELECT id FROM organizations LIMIT 1),
    'Success Story: Local Restaurant',
    'Case study about how a local restaurant increased revenue by 40% using AI',
    'Meet Sarah, owner of "Bella''s Bistro" - a small family restaurant that was struggling with...',
    'post',
    'published',
    'urgent',
    ARRAY['Case Study', 'Restaurant', 'Success Story', 'Revenue Growth'],
    'Small restaurant owner makes $50K more per month with this ONE AI trick',
    94,
    9.3,
    96,
    91,
    ARRAY['Facebook', 'Instagram', 'LinkedIn', 'Twitter'],
    12500,
    890,
    156,
    234,
    true,
    false,
    NOW() - INTERVAL '14 days',
    NOW() - INTERVAL '7 days'
),
(
    '550e8400-e29b-41d4-a716-446655440005',
    (SELECT id FROM auth.users LIMIT 1),
    (SELECT id FROM organizations LIMIT 1),
    'AI Security Concerns Addressed',
    'Educational content addressing common security concerns about AI implementation',
    'Many business owners are hesitant to implement AI due to security concerns. Let''s address the top 5 myths...',
    'post',
    'ideas',
    'medium',
    ARRAY['Security', 'AI', 'Education', 'Myths'],
    'The TRUTH about AI security that tech companies don''t want you to know',
    72,
    6.8,
    84,
    76,
    ARRAY['LinkedIn', 'Medium', 'Blog'],
    0,
    0,
    0,
    0,
    false,
    true,
    NOW() - INTERVAL '3 days',
    NOW() - INTERVAL '1 day'
),
(
    '550e8400-e29b-41d4-a716-446655440006',
    (SELECT id FROM auth.users LIMIT 1),
    (SELECT id FROM organizations LIMIT 1),
    'Integration Workflow Diagram',
    'Visual representation of how our AI agents integrate with existing business systems',
    'Infographic showing the step-by-step integration process from initial setup to full automation...',
    'image',
    'in-progress',
    'low',
    ARRAY['Integration', 'Workflow', 'Visual', 'Process'],
    'See exactly how AI integrates with your current systems (it''s easier than you think)',
    68,
    6.2,
    79,
    73,
    ARRAY['Pinterest', 'LinkedIn', 'Instagram'],
    0,
    0,
    0,
    0,
    false,
    false,
    NOW() - INTERVAL '4 days',
    NOW() - INTERVAL '6 hours'
);

-- Insert sample comments
INSERT INTO content_comments (
    content_item_id,
    author_id,
    content
) VALUES 
(
    '550e8400-e29b-41d4-a716-446655440004',
    (SELECT id FROM auth.users LIMIT 1),
    'This is an amazing success story! The results speak for themselves.'
),
(
    '550e8400-e29b-41d4-a716-446655440004',
    (SELECT id FROM auth.users LIMIT 1),
    'We should create more case studies like this one. Very compelling content.'
);

-- Insert sample activity log entries
INSERT INTO content_activity_log (
    content_item_id,
    user_id,
    action,
    details
) VALUES 
(
    '550e8400-e29b-41d4-a716-446655440001',
    (SELECT id FROM auth.users LIMIT 1),
    'created',
    '{"title": "AI Revolution in Small Business"}'
),
(
    '550e8400-e29b-41d4-a716-446655440002',
    (SELECT id FROM auth.users LIMIT 1),
    'moved',
    '{"from": "ideas", "to": "in-progress"}'
),
(
    '550e8400-e29b-41d4-a716-446655440004',
    (SELECT id FROM auth.users LIMIT 1),
    'starred',
    '{"starred": true}'
);
